# NOTE: Seed constants below are inserted only into new `quality_*` tables by
# `scripts/seed_quality_rbac.py`; they do not replace existing source data.
QUALITY_DEPARTMENTS = [
    {"code": "BGD", "name": "Ban Giam Doc", "short_name": "BGD"},
    {"code": "KDH", "name": "Khoa Dieu Hanh", "short_name": "KDH"},
    {"code": "KCCNBV", "name": "Khoa Cap Cuu Ngoai Benh Vien", "short_name": "KCCNBV"},
    {"code": "QLCL", "name": "Quan Ly Chat Luong", "short_name": "QLCL"},
]

QUALITY_PERMISSIONS = [
    ("portal:view", "Portal view", "portal"),
    ("profile:view", "Profile view", "portal"),
    ("dashboard:view", "Dashboard view", "dashboard"),
    ("dashboard:view_bgd", "Dashboard BGD view", "dashboard"),
    ("dashboard:view_kdh", "Dashboard KDH view", "dashboard"),
    ("dashboard:view_kccnbv", "Dashboard KCCNBV view", "dashboard"),
    ("dashboard:view_quality", "Dashboard quality view", "dashboard"),
    ("dashboard:export_snapshot", "Dashboard snapshot export", "dashboard"),
    ("reports:input:view", "Manual input view", "reports_input"),
    ("reports:input:create", "Manual input create", "reports_input"),
    ("reports:input:update_own", "Manual input update own draft", "reports_input"),
    ("reports:input:update_department", "Manual input update department", "reports_input"),
    ("reports:input:delete_draft", "Manual input delete draft", "reports_input"),
    ("reports:input:submit", "Manual input submit", "reports_input"),
    ("reports:import:view", "Excel import view", "reports_import"),
    ("reports:import:upload", "Excel import upload", "reports_import"),
    ("reports:import:preview", "Excel import preview", "reports_import"),
    ("reports:import:confirm", "Excel import confirm", "reports_import"),
    ("reports:import:cancel_own", "Excel import cancel own", "reports_import"),
    ("reports:import:cancel_any", "Excel import cancel any", "reports_import"),
    ("reports:review:view", "Review view", "reports_review"),
    ("reports:review:approve", "Review approve", "reports_review"),
    ("reports:review:reject", "Review reject", "reports_review"),
    ("reports:period_lock:view", "Period lock view", "reports_lock"),
    ("reports:period_lock:lock", "Period lock", "reports_lock"),
    ("reports:period_lock:unlock", "Period unlock", "reports_lock"),
    ("indicators:view", "Indicator catalog view", "indicators"),
    ("indicators:manage_catalog", "Indicator catalog manage", "indicators"),
    ("indicators:manage_thresholds", "Indicator thresholds manage", "indicators"),
    ("indicators:view_results", "Indicator results view", "indicators"),
    ("indicators:recalculate", "Indicator recalculation", "indicators"),
    ("etl:view", "ETL view", "etl"),
    ("etl:run", "ETL run", "etl"),
    ("etl:rerun", "ETL rerun", "etl"),
    ("etl:view_logs", "ETL logs view", "etl"),
    ("etl:view_data_quality", "Data quality logs view", "etl"),
    ("etl:cancel_run", "ETL cancel run", "etl"),
    ("admin:view", "Admin view", "admin"),
    ("admin:manage_users", "Admin manage users", "admin"),
    ("admin:manage_roles", "Admin manage roles", "admin"),
    ("admin:manage_permissions", "Admin manage permissions", "admin"),
    ("admin:manage_scopes", "Admin manage scopes", "admin"),
    ("admin:view_audit_logs", "Audit logs view", "admin"),
    ("reports:export:view", "Report export view", "reports_export"),
    ("reports:export:excel", "Report export Excel", "reports_export"),
    ("reports:export:pdf", "Report export PDF", "reports_export"),
    ("reports:export:word", "Report export Word", "reports_export"),
    ("ai_agent:use", "AI agent use", "ai_agent"),
    ("ai_agent:manage_sources", "AI agent source management", "ai_agent"),
]

QUALITY_ROLES = {
    "system_admin": {
        "name": "System admin",
        "description": "Full access to QLCL Web.",
        "is_system": True,
        "permissions": [code for code, _, _ in QUALITY_PERMISSIONS],
    },
    "quality_admin": {
        "name": "Quality admin",
        "description": "Manage QLCL indicators, review, period lock, and audit.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "dashboard:view_bgd",
            "dashboard:view_kdh",
            "dashboard:view_kccnbv",
            "dashboard:view_quality",
            "dashboard:export_snapshot",
            "reports:input:view",
            "reports:input:create",
            "reports:input:update_department",
            "reports:input:delete_draft",
            "reports:input:submit",
            "reports:import:view",
            "reports:import:upload",
            "reports:import:preview",
            "reports:import:confirm",
            "reports:import:cancel_any",
            "reports:review:view",
            "reports:review:approve",
            "reports:review:reject",
            "reports:period_lock:view",
            "reports:period_lock:lock",
            "reports:period_lock:unlock",
            "indicators:view",
            "indicators:manage_catalog",
            "indicators:manage_thresholds",
            "indicators:view_results",
            "indicators:recalculate",
            "etl:view",
            "etl:run",
            "etl:rerun",
            "etl:view_logs",
            "etl:view_data_quality",
            "reports:export:view",
            "reports:export:excel",
            "admin:view",
            "admin:view_audit_logs",
        ],
    },
    "department_manager": {
        "name": "Department manager",
        "description": "Review and view data within assigned scope.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "reports:input:view",
            "reports:import:view",
            "reports:review:view",
            "reports:review:approve",
            "reports:review:reject",
            "reports:period_lock:view",
            "indicators:view",
            "indicators:view_results",
            "etl:view",
            "etl:view_data_quality",
            "reports:export:view",
            "reports:export:excel",
        ],
    },
    "data_entry": {
        "name": "Data entry",
        "description": "Create and submit manual input/import drafts.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "reports:input:view",
            "reports:input:create",
            "reports:input:update_own",
            "reports:input:delete_draft",
            "reports:input:submit",
            "reports:import:view",
            "reports:import:upload",
            "reports:import:preview",
            "reports:import:cancel_own",
        ],
    },
    "dashboard_viewer": {
        "name": "Dashboard viewer",
        "description": "View dashboards and exportable summaries within scope.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "indicators:view_results",
            "reports:export:view",
        ],
    },
    "etl_operator": {
        "name": "ETL operator",
        "description": "Run ETL/calculation jobs and inspect logs.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "etl:view",
            "etl:run",
            "etl:rerun",
            "etl:view_logs",
            "etl:view_data_quality",
            "indicators:view_results",
        ],
    },
    "auditor": {
        "name": "Auditor",
        "description": "Read-only access to locked data and audit logs.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "reports:review:view",
            "reports:period_lock:view",
            "indicators:view_results",
            "etl:view",
            "etl:view_logs",
            "etl:view_data_quality",
            "admin:view_audit_logs",
        ],
    },
    "ai_agent_user": {
        "name": "AI agent user",
        "description": "Use Agent-AI when Phase 10 integration is enabled.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "ai_agent:use",
        ],
    },
}

QUALITY_INDICATORS = [
    {
        "code": f"CS{index}",
        "name": f"Chỉ số lâm sàng CS{index}" if index <= 26 else f"Chỉ số khoa phòng CS{index}",
        "group_code": "MVP",
        "formula_python_key": f"cs{index}",
        "frequency": "daily",
        "source_type": "calculated" if index <= 26 else "manual",
        "owner_department_code": "KDH" if index <= 10 else ("KCCNBV" if index <= 26 else "QLCL"),
    }
    for index in range(1, 54)
]

# Danh sách các biến số chất lượng nhập thủ công khoa phòng cs24-cs53
QUALITY_VARIABLES = []

# Định nghĩa các chỉ số từ cs24 đến cs53
variable_definitions = {
    "cs24": ("CS24: Trung bình thời gian tại hiện trường (phút)", "QLCL", "number"),
    "cs24cg": ("CS24: TB thời gian tại hiện trường - Cần Giờ", "QLCL", "number"),
    "cs24q8": ("CS24: TB thời gian tại hiện trường - Quận 8", "QLCL", "number"),
    "cs24td": ("CS24: TB thời gian tại hiện trường - Thủ Đức", "QLCL", "number"),
    "cs24ub": ("CS24: TB thời gian tại hiện trường - Ung Bướu", "QLCL", "number"),
    "cs25": ("CS25: Trung bình thời gian chuyển đến bệnh viện (phút)", "QLCL", "number"),
    "cs25cg": ("CS25: TB thời gian chuyển đến BV - Cần Giờ", "QLCL", "number"),
    "cs25q8": ("CS25: TB thời gian chuyển đến BV - Quận 8", "QLCL", "number"),
    "cs25td": ("CS25: TB thời gian chuyển đến BV - Thủ Đức", "QLCL", "number"),
    "cs25ub": ("CS25: TB thời gian chuyển đến BV - Ung Bướu", "QLCL", "number"),
    "cs28": ("CS28: Tỷ lệ thiết bị y tế được bảo trì (%)", "QLCL", "number"),
    "cs29": ("CS29: Tỷ lệ hoàn tất kiểm định thiết bị (%)", "QLCL", "number"),
    "cs30": ("CS30: Tỷ lệ cung ứng đủ số lượng VTYT (%)", "QLCL", "number"),
    "cs31": ("CS31: Tỷ lệ tai nạn thương tích vật sắc nhọn (%)", "QLCL", "number"),
    "cs32": ("CS32: Tỷ lệ tuân thủ vệ sinh tay (%)", "QLCL", "number"),
    "cs33": ("CS33: Sự hài lòng chung về Trung tâm (%)", "QLCL", "number"),
    "cs34": ("CS34: Điểm tiêu chí cải cách hành chính (A/B/C/D)", "QLCL", "text"),
    "cs35": ("CS35: Điểm tiêu chí cơ sở xanh-sạch-đẹp (%)", "QLCL", "number"),
    "cs36": ("CS36: Tỷ lệ sự cố ngoài y khoa nghiêm trọng (%)", "QLCL", "number"),
    "cs37": ("CS37: Tỷ lệ xe cứu thương kết nối định vị (%)", "QLCL", "number"),
    "cs38": ("CS38: Hiệu suất sử dụng xe cứu thương (%)", "QLCL", "number"),
    "cs39": ("CS39: Tỷ lệ nhân viên tuyển dụng theo đề án (%)", "QLCL", "number"),
    "cs40": ("CS40: Số sự cố y khoa bắt buộc báo cáo", "QLCL", "number"),
    "cs41": ("CS41: Tỷ lệ hài lòng của người dân (%)", "QLCL", "number"),
    "cs42": ("CS42: Điểm tiêu chí chất lượng Trung tâm", "QLCL", "number"),
    "cs43": ("CS43: Điểm tiêu chí chất lượng Trạm vệ tinh", "QLCL", "number"),
    "cs44": ("CS44: Tổng số Trạm vệ tinh Cấp cứu 115", "QLCL", "number"),
    "cs45": ("CS45: Tỷ lệ Trạm vệ tinh kết nối điều hành (%)", "QLCL", "number"),
    "cs46": ("CS46: Tỷ lệ nhân viên được đào tạo liên tục (%)", "QLCL", "number"),
    "cs47": ("CS47: Số công tác phục vụ sự kiện chính trị", "QLCL", "number"),
    "cs48": ("CS48: Số cơ sở y tế được hỗ trợ chuyên môn", "QLCL", "number"),
    "cs49": ("CS49: Số lớp đào tạo liên tục cho NVYT", "QLCL", "number"),
    "cs50": ("CS50: Số lớp đào tạo cho cộng đồng", "QLCL", "number"),
    
    # Financial metrics cs51 to cs53 with satellite suffixes
    "cs51": ("CS51: Tổng số biên lai/phiên trực - Trung tâm", "QLCL", "number"),
    "cs51cg": ("CS51: Tổng số biên lai/phiên trực - Cần Giờ", "QLCL", "number"),
    "cs51q8": ("CS51: Tổng số biên lai/phiên trực - Quận 8", "QLCL", "number"),
    "cs51td": ("CS51: Tổng số biên lai/phiên trực - Thủ Đức", "QLCL", "number"),
    "cs51ub": ("CS51: Tổng số biên lai/phiên trực - Ung Bướu", "QLCL", "number"),
    
    "cs52": ("CS52: TB số tiền/Biên lai - Trung tâm", "QLCL", "number"),
    "cs52cg": ("CS52: TB số tiền/Biên lai - Cần Giờ", "QLCL", "number"),
    "cs52q8": ("CS52: TB số tiền/Biên lai - Quận 8", "QLCL", "number"),
    "cs52td": ("CS52: TB số tiền/Biên lai - Thủ Đức", "QLCL", "number"),
    "cs52ub": ("CS52: TB số tiền/Biên lai - Ung Bướu", "QLCL", "number"),
    
    "cs53": ("CS53: Số tiền thu được/phiên trực - Trung tâm", "QLCL", "number"),
    "cs53cg": ("CS53: Số tiền thu được/phiên trực - Cần Giờ", "QLCL", "number"),
    "cs53q8": ("CS53: Số tiền thu được/phiên trực - Quận 8", "QLCL", "number"),
    "cs53td": ("CS53: Số tiền thu được/phiên trực - Thủ Đức", "QLCL", "number"),
    "cs53ub": ("CS53: Số tiền thu được/phiên trực - Ung Bướu", "QLCL", "number"),
}

for code, (name, dept, dtype) in variable_definitions.items():
    QUALITY_VARIABLES.append({
        "variable_code": code,
        "name": name,
        "group_code": "CL" if "cs2" in code or "cs3" in code or "cs4" in code else "TC",
        "data_type": dtype,
        "source_type": "manual",
        "required": True if code in ["cs24", "cs25", "cs28", "cs32", "cs33", "cs41", "cs51", "cs52", "cs53"] else False,
        "min_value": 0 if dtype == "number" else None,
    })

