# NOTE: Seed constants below are inserted only into new `quality_*` tables by
# `scripts/seed_quality_rbac.py`; they do not replace existing source data.
QUALITY_DEPARTMENTS = [
    {"code": "BGD", "name": "Ban Giam Doc", "short_name": "BGD"},
    {"code": "KDH", "name": "Khoa Dieu Hanh", "short_name": "KDH"},
    {"code": "KCCNBV", "name": "Khoa Cap Cuu Ngoai Benh Vien", "short_name": "KCCNBV"},
    {"code": "QLCL", "name": "Quan Ly Chat Luong", "short_name": "QLCL"},
]

QUALITY_PERMISSIONS = [
    ("portal:view", "Portal view", "portal"),
    ("profile:view", "Profile view", "portal"),
    ("dashboard:view", "Dashboard view", "dashboard"),
    ("dashboard:view_bgd", "Dashboard BGD view", "dashboard"),
    ("dashboard:view_kdh", "Dashboard KDH view", "dashboard"),
    ("dashboard:view_kccnbv", "Dashboard KCCNBV view", "dashboard"),
    ("dashboard:view_quality", "Dashboard quality view", "dashboard"),
    ("dashboard:export_snapshot", "Dashboard snapshot export", "dashboard"),
    ("reports:input:view", "Manual input view", "reports_input"),
    ("reports:input:create", "Manual input create", "reports_input"),
    ("reports:input:update_own", "Manual input update own draft", "reports_input"),
    ("reports:input:update_department", "Manual input update department", "reports_input"),
    ("reports:input:delete_draft", "Manual input delete draft", "reports_input"),
    ("reports:input:submit", "Manual input submit", "reports_input"),
    ("reports:import:view", "Excel import view", "reports_import"),
    ("reports:import:upload", "Excel import upload", "reports_import"),
    ("reports:import:preview", "Excel import preview", "reports_import"),
    ("reports:import:confirm", "Excel import confirm", "reports_import"),
    ("reports:import:cancel_own", "Excel import cancel own", "reports_import"),
    ("reports:import:cancel_any", "Excel import cancel any", "reports_import"),
    ("reports:review:view", "Review view", "reports_review"),
    ("reports:review:approve", "Review approve", "reports_review"),
    ("reports:review:reject", "Review reject", "reports_review"),
    ("reports:period_lock:view", "Period lock view", "reports_lock"),
    ("reports:period_lock:lock", "Period lock", "reports_lock"),
    ("reports:period_lock:unlock", "Period unlock", "reports_lock"),
    ("indicators:view", "Indicator catalog view", "indicators"),
    ("indicators:manage_catalog", "Indicator catalog manage", "indicators"),
    ("indicators:manage_thresholds", "Indicator thresholds manage", "indicators"),
    ("indicators:view_results", "Indicator results view", "indicators"),
    ("indicators:recalculate", "Indicator recalculation", "indicators"),
    ("etl:view", "ETL view", "etl"),
    ("etl:run", "ETL run", "etl"),
    ("etl:rerun", "ETL rerun", "etl"),
    ("etl:view_logs", "ETL logs view", "etl"),
    ("etl:view_data_quality", "Data quality logs view", "etl"),
    ("etl:cancel_run", "ETL cancel run", "etl"),
    ("admin:view", "Admin view", "admin"),
    ("admin:manage_users", "Admin manage users", "admin"),
    ("admin:manage_roles", "Admin manage roles", "admin"),
    ("admin:manage_permissions", "Admin manage permissions", "admin"),
    ("admin:manage_scopes", "Admin manage scopes", "admin"),
    ("admin:view_audit_logs", "Audit logs view", "admin"),
    ("reports:export:view", "Report export view", "reports_export"),
    ("reports:export:excel", "Report export Excel", "reports_export"),
    ("reports:export:pdf", "Report export PDF", "reports_export"),
    ("reports:export:word", "Report export Word", "reports_export"),
    ("ai_agent:use", "AI agent use", "ai_agent"),
    ("ai_agent:manage_sources", "AI agent source management", "ai_agent"),
]

QUALITY_ROLES = {
    "system_admin": {
        "name": "System admin",
        "description": "Full access to QLCL Web.",
        "is_system": True,
        "permissions": [code for code, _, _ in QUALITY_PERMISSIONS],
    },
    "quality_admin": {
        "name": "Quality admin",
        "description": "Manage QLCL indicators, review, period lock, and audit.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "dashboard:view_bgd",
            "dashboard:view_kdh",
            "dashboard:view_kccnbv",
            "dashboard:view_quality",
            "dashboard:export_snapshot",
            "reports:input:view",
            "reports:input:create",
            "reports:input:update_department",
            "reports:input:delete_draft",
            "reports:input:submit",
            "reports:import:view",
            "reports:import:upload",
            "reports:import:preview",
            "reports:import:confirm",
            "reports:import:cancel_any",
            "reports:review:view",
            "reports:review:approve",
            "reports:review:reject",
            "reports:period_lock:view",
            "reports:period_lock:lock",
            "reports:period_lock:unlock",
            "indicators:view",
            "indicators:manage_catalog",
            "indicators:manage_thresholds",
            "indicators:view_results",
            "indicators:recalculate",
            "etl:view",
            "etl:run",
            "etl:rerun",
            "etl:view_logs",
            "etl:view_data_quality",
            "reports:export:view",
            "reports:export:excel",
            "admin:view",
            "admin:view_audit_logs",
        ],
    },
    "department_manager": {
        "name": "Department manager",
        "description": "Review and view data within assigned scope.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "reports:input:view",
            "reports:import:view",
            "reports:review:view",
            "reports:review:approve",
            "reports:review:reject",
            "reports:period_lock:view",
            "indicators:view",
            "indicators:view_results",
            "etl:view",
            "etl:view_data_quality",
            "reports:export:view",
            "reports:export:excel",
        ],
    },
    "data_entry": {
        "name": "Data entry",
        "description": "Create and submit manual input/import drafts.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "reports:input:view",
            "reports:input:create",
            "reports:input:update_own",
            "reports:input:delete_draft",
            "reports:input:submit",
            "reports:import:view",
            "reports:import:upload",
            "reports:import:preview",
            "reports:import:cancel_own",
        ],
    },
    "dashboard_viewer": {
        "name": "Dashboard viewer",
        "description": "View dashboards and exportable summaries within scope.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "indicators:view_results",
            "reports:export:view",
        ],
    },
    "etl_operator": {
        "name": "ETL operator",
        "description": "Run ETL/calculation jobs and inspect logs.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "etl:view",
            "etl:run",
            "etl:rerun",
            "etl:view_logs",
            "etl:view_data_quality",
            "indicators:view_results",
        ],
    },
    "auditor": {
        "name": "Auditor",
        "description": "Read-only access to locked data and audit logs.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "dashboard:view",
            "reports:review:view",
            "reports:period_lock:view",
            "indicators:view_results",
            "etl:view",
            "etl:view_logs",
            "etl:view_data_quality",
            "admin:view_audit_logs",
        ],
    },
    "ai_agent_user": {
        "name": "AI agent user",
        "description": "Use Agent-AI when Phase 10 integration is enabled.",
        "is_system": True,
        "permissions": [
            "portal:view",
            "profile:view",
            "ai_agent:use",
        ],
    },
}

QUALITY_INDICATORS = [
    {
        "code": f"CS{index}",
        "name": f"Indicator CS{index}",
        "group_code": "MVP",
        "formula_python_key": f"cs{index}",
        "frequency": "daily",
        "source_type": "mixed",
        "owner_department_code": "QLCL",
    }
    for index in range(1, 11)
]

QUALITY_VARIABLES = [
    {
        "variable_code": f"A{index}",
        "name": f"Variable A{index}",
        "group_code": "A",
        "data_type": "number",
        "source_type": "manual",
        "required": True,
        "min_value": 0,
    }
    for index in range(1, 6)
] + [
    {
        "variable_code": f"B{index}",
        "name": f"Variable B{index}",
        "group_code": "B",
        "data_type": "number",
        "source_type": "manual",
        "required": False,
        "min_value": 0,
    }
    for index in range(1, 6)
]
